### ISSUE TITLE
Can I run the code without Intel compiler？

### ISSUE THREAD

**Issue by jzpwhu1996** [MaaniGhaffari/cvo-rgbd#1]

**Comment by MaaniGhaffari** [comment]
Yes. But it'll run slower if the compiler doesn't support vectorization. If you use the latest g++, then it might work well too.

**Comment by jzpwhu1996** [comment]
Thanks a lot, I have already run the code. Great job! 
And I have a question about the terminal output. After I ran the code with a TUM dataset, I got the information "Total time for 1352 frames is:  315.547575s wall, 1468.450000s user + 65.280000s system = 1533.730000s CPU (486.1%)"
Could you please tell me what  "wall", "user","system" and "486.1%" mean? 
Thanks a lot!

**Comment by tzuyuan** [comment]
Hi,

This is the output from boost timer. You can find more information here: https://www.boost.org/doc/libs/1_54_0/libs/timer/doc/cpu_timers.html.

Wall time is the time that you can measure from a clock hanging on a wall. user is the user CPU time. system is the system CPU time. 486.1% means the total CPU time represents 486.1% of the wall time.

**Comment by jzpwhu1996** [comment]
> Hi,
> 
> This is the output from boost timer. You can find more information here: https://www.boost.org/doc/libs/1_54_0/libs/timer/doc/cpu_timers.html.
> 
> Wall time is the time that you can measure from a clock hanging on a wall. user is the user CPU time. system is the system CPU time. 486.1% means the total CPU time represents 486.1% of the wall time.

Thanks a lot ！
